### ISSUE TITLE
Crash when switching to currency options

### ISSUE THREAD

**Issue by Ananas-Kuchen** [Myzel394/NumberHub#21]
Version 0.2.0 immediately crashes when using the unit converter to switch to currency only. which does not happen in version 0.1.3

Please add month, year, even above for time on the unit converter

Also add an option to change the unit converter list mode to not only scroll down, but there is an infinite side scrolling mode, thank you

**Comment by Crazy-Unicooorn** [comment]
Can confirm the crash on going to unit converter

Android 13
One UI 5.1
App version 0.2.0 (20)

**Comment by Myzel394** [comment]
I'm working on it, a patch should come soon. Turns out I did fix this already but forgot to commit :P

**Comment by Myzel394** [comment]
All right guys, I've pushed an update (see [0.2.1](https://github.com/Myzel394/NumberHub/releases/tag/v0.2.1)). Sorry for the inconveniences

**Comment by Ananas-Kuchen** [comment]
> All right guys, I've pushed an update (see [0.2.1](https://github.com/Myzel394/NumberHub/releases/tag/v0.2.1)). Sorry for the inconveniences

finally. after I tested it it seems like there is no problem anymore. thank you.
