### ISSUE TITLE
How to use new converter?

### ISSUE THREAD

**Issue by Humorist2601** [Myzel394/NumberHub#23]
Sorry If I am just being an idiot over here but I cant figure out how to convert binary to decimal in the new converter Update. 

P.S love you for maintaining and improving this awesone app.

**Comment by Myzel394** [comment]
Hey @Humorist2601,

the functionality of the converter hasn't changed. If you want to convert from binary to decimal, you'l need to make sure Binary is selected on the left and Decimal is selected on the right.

What has changed is the keyboard. Given binary as the example, you will only see "0" and "1" - as those are the only keys relevant for binary input.

Hope I could help clarify the update :)
