### ISSUE TITLE
App not installed as package conflicts with an existing package

### ISSUE THREAD

**Issue by kaoneko** [Myzel394/NumberHub#5]
That is the message I get when trying to update from NumberHub version NumberHub (1) to NumberHub version NumberHub (2).

Steps to reproduce: 
- install version NumberHub (1)
- install version NumberHub (2)
- tap Update when asked _Do you want to update this app?_

**Comment by kaoneko** [comment]
Does it have to do something with the fact that both releases are signed with debug keys?

**Comment by Myzel394** [comment]
Ahh damn it. I knew something was off, but couldn't tell what it was. Let me take a look at that...

**Comment by Myzel394** [comment]
> Could it have something to do with the fact that both releases are signed with a debug certificate?

How did you find that out? Is there some tool in Android Studio to see that?

**Comment by Myzel394** [comment]
TODO:

- [ ] Fix CI:CD
- [ ] Replace current releases

**Comment by ojppe** [comment]
Workaround:
1. backup settings (3 dots in settings)
2. delete app
3. install update
4. restore settings

**Comment by kaoneko** [comment]
> > Could it have something to do with the fact that both releases are signed with a debug certificate?
> 
> How did you find that out? Is there some tool in Android Studio to see that?

Undoubtedly. But I saw it in [App Manager](https://github.com/MuntashirAkon/AppManager) on the _Signatures_ tab when inspecting NumberHub.

**Comment by Myzel394** [comment]
All right guys, everything should be fixed now. Thanks for opening the issue @kaoneko, I somehow completely missed setting up the signing key! Make sure to reinstall the app
